name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: openjdk:17-oracle
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    container: openjdk:17-oracle
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          ./gradlew build
          ./gradlew installdist

  deploy:
    runs-on: ubuntu-latest
    container: openjdk:17-oracle
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: ls

